airflow:
  #Cluster volume mount.
  extraVolumeMounts:
    - name: local-dags
      mountPath: /opt/airflow/dags
  #Load dags.
  extraVolumes:
    - name: local-dags
      hostPath:
        path: /mnt/host
  #Config webserver.
  config:
    AIRFLOW__WEBSERVER__BASE_URL: "http://localhost/"
    ENV: "dev"
ingress:
  enabled: true
  web:
    annotations:
      kubernetes.io/ingress.class: "nginx"
    host: localhost
    tls:
      enabled: true
  flower:
    annotations:
      kubernetes.io/ingress.class: "nginx"
    host: localhost
    tls:
      enabled: true